MIN_DISTANCE = 3

THRESHOLD = {
    1 : 1,
    6 : 3,
    12 : 5
}

ALL_ROLES = [
        {
            "name" : "ADVISOR",
            "examples" : [
                "ADVISOR",
                "ADVOCATE",
                "ATTORNEY",
                "BLOCKCHAIN ADVISOR",
                "BOARD ADVISOR",
                "BUSINESS ADVISOR",
                "BUSINESS EXPERT",
                "CCO",
                "CHIEF COMPLIANCE",
                "CHIEF COMPLIANCE OFFICER",
                "COMPLIANCE",
                "CONSULTANT",
                "ENDORSER",
                "FINANCIAL ADVISOR",
                "ICO ADVISOR",
                "INITIAL COIN OFFERING ADVISOR",
                "LAWYER",
                "LEGAL",
                "LEGAL ADVISOR",
                "SENIOR ADMINISTRATOR",
                "STRATEGIC ADVISOR",
                "STRATEGY",
                "TECHNICAL ADVISOR",
                "CRYPTO EXPERT",
                "CRYPTOCURRENCY EXPERT",
                "EARLY SUPPORTER",
                "GENERAL COUNSEL",
                "INDUSTRY EXPERT",
                "MENTOR",
                "MENTORS",
                "PROFESSOR"
            ]
        },
        {
            "name" : "DEVELOPER",
            "examples" : [
                "ART",
                "ARTIFICIAL INTELLIGENCE",
                "ARTIFICIAL INTELLIGENCE EXPERT",
                "ARTIFICIAL INTELLIGENCE RESEARCHER",
                "BACKEND DEVELOPER",
                "BC",
                "BLOCKCHAIN",
                "BLOCKCHAIN DEVELOPER",
                "BLOCKCHAIN EXPERT",
                "BLOCKCHAIN ENGINEER",
                "CORE DEVELOPER",
                "DATA SCIENCE",
                "DATA SCIENCE EXPERT",
                "DATA SCIENCE RESEARCHER",
                "DEV",
                "DEVELOPER",
                "DEVELOPMENT",
                "ENGINEER",
                "FRONTEND DEVELOPER",
                "FULL STACK DEVELOPER",
                "GRAPHIC  DEVELOPER",
                "IOS DEVELOPER",
                "LEAD DEVELOPER",
                "MACHINE LEARNING",
                "MACHINE LEARNING EXPERT",
                "MACHINE LEARNING RESEARCHER",
                "PRODUCER",
                "PROGRAMMER",
                "RESEARCHER",
                "SENIOR DEVELOPER",
                "SENIOR SOFTWARE ENGINEER",
                "SOFTWARE DEVELOPER",
                "SOFTWARE ENGINEER",
                "SW DEVELOPER",
                "SW ENGINEER",
                "TECHNOLOGY",
                "UI DEVELOPER",
                "USER EXPERIENCE DEVELOPER",
                "UX  DEVELOPER",
                "WEB DEVELOPER",
                "DESIGNER",
                "GRAPHIC DESIGNER",
                "UI",
                "UI DESIGNER",
                "USER INTERFACE DEVELOPER",
                "USER INTERFACE DESIGNER",
                "USER EXPERIENCE DESIGNER",
                "UX",
                "UX DESIGNER",
                "3D ARTIST",
                "BACKEND",
                "BACKOFFICE",
                "BLOCKCHAIN & CRYPTO EXPERT",
                "BLOCKCHAIN DATA SCIENTIST",
                "BLOCKCHAIN DEVELOPING EXPERT",
                "BLOCKCHAIN SPECIALIST",
                "BLOCKCHAIN TECH",
                "BUSINESS INTELLIGENCE",
                "CODER",
                "CONCEPT ARTIST",
                "CONTENT CREATOR",
                "CONTENT CURATOR",
                "CONTENT CURATOR & TESTER",
                "CONTENT PRODUCER",
                "CONTENT PRODUCTION",
                "CONTENT SPECIALIST",
                "COPYWRITER",
                "CREATIVE",
                "CREATOR",
                "CRYPTOGRAPHER",
                "DATA ANALYST",
                "DATA SCIENTIST",
                "DATABASE ADMINISTRATOR",
                "DIGITAL PRODUCER",
                "ENGINEERING",
                "FRONT END",
                "FRONTEND",
                "GRAPHIC ARTIST",
                "GRAPHICS",
                "ILLUSTRATOR",
                "INTERN",
                "MATHEMATICIAN",
                "MEMBER",
                "PRODUCER",
                "QUALITY ASSURANCE",
                "QUALITY ASSURANCE ANALYST",
                "SENIOR DATA ANALYST",
                "SENIOR DATA SCIENTIST",
                "SENIOR TECHNICAL SPECIALIST",
                "SOFTWARE",
                "SOFTWARE ENGINEERING",
                "SOFTWARE INTERN",
                "STYLIST",
                "SUPPORT",
                "SUPPORT TEAM MEMBER",
                "SYSTEM ADMINISTRATION",
                "SYSTEM ADMINISTRATOR",
                "TEAM MEMBER",
                "TECH",
                "TECHNICAL",
                "TECHNICAL DEPLOYMENTS",
                "TECHNICAL DOCUMENTATION SPECIALIST",
                "TECHNICAL WRITER",
                "TRANSLATIONS",
                "TRANSLATOR",
                "USER EXPERIENCE",
                "WRITER"
            ]
        },
        {
            "name" : "FINANCE AND ADMINISTRATION",
            "examples" : [
                "ACCOUNTANT",
                "CHIEF PROCUREMENT",
                "CHIEF PROCUREMENT OFFICER",
                "MARKET ANALYST",
                "TRADING ANALYST",
                "ACCOUNT EXECUTIVE",
                "ACCOUNT OFFICER",
                "ADMINISTRATION",
                "ADMINISTRATIVE",
                "ADMINISTRATIVE ASSISTANT",
                "ANALYTICS",
                "ASSISTANT",
                "BUSINESS ASSISTANT",
                "BUSINESS ASSOCIATE",
                "CONTROLLER",
                "CRYPTO ANALYST & TRADER",
                "CRYPTOCURRENCY SPECIALIST",
                "DIGITAL ASSET SPECIALIST",
                "ECONOMIC",
                "ECONOMIST",
                "ESCROW",
                "EXECUTIVE ASSISTANT",
                "FINANCE",
                "FINANCIAL",
                "FINANCIAL ANALYST",
                "FINANCIAL CONTROLLER",
                "FINANCIAL EXPERT",
                "FINANCIAL SPECIALIST",
                "INSURANCE",
                "MEMBER SUPPORT",
                "PAYMENTS",
                "PROFESSIONAL TRADER",
                "TOKEN ECONOMICS",
                "TOKEN ECONOMIST",
                "TRADER"
            ]
        },
        {
            "name" : "FOUNDER",
            "examples" : [
                "BOARD MEMBER",
                "CO FOUNDER",
                "ENTREPRENEUR",
                "FOUNDER",
                "PARTNER",
                "PRESIDENT",
                "ASSOCIATE",
                "FOUNDATION COUNCIL",
                "FOUNDATION MEMBER",
                "FOUNDING MEMBER"
            ]
        },
        {
            "name" : "INVESTOR",
            "examples" : [
                "BUSINESSANGEL",
                "CO FUNDER",
                "FUNDER",
                "INVESTOR",
                "INVESTMENT",
                "BUSINESS ANGEL",
                "CAPITAL MARKETS",
                "FENBUSHI CAPITAL",
                "VENTURE"
            ]
        },
        {
            "name" : "MANAGER",
            "examples" : [
                "AGENT",
                "BUSINESS DEVELOPMENT",
                "CEO",
                "CEO MARKETING",
                "C.E.O.",
                "CFO",
                "CHAIRMAN",
                "CHIEF EXECUTIVE",
                "CHIEF EXECUTIVE OFFICER",
                "CHIEF EXECUTIVE OFFICER MARKETING",
                "CHIEF FINANCIAL",
                "CHIEF FINANCIAL OFFICER",
                "CHIEF MARKETING",
                "CHIEF TECHNICAL",
                "CHIEF TECHNICAL OFFICER",
                "CHIEF TECHNOLOGY",
                "CHIEF TECHNOLOGY OFFICER",
                "CHIEF INFORMATION",
                "CHIEF INFORMATION OFFICER",
                "CIO",
                "CHIEF MARKETING OFFICER",
                "CMO",
                "COMMUNITY MANAGER",
                "COORDINATOR",
                "CPO",
                "CSO",
                "CTO",
                "DIRECTOR",
                "MANAGER",
                "MANAGEMENT",
                "COMMUNITY MANAGEMENT",
                "PRODUCT MANAGER",
                "BUSINESS HEAD",
                "EXECUTIVE",
                "EXECUTIVE PRODUCER",
                "HUMAN RESOURCES",
                "SENIOR EXECUTIVE"
            ]
        },
        {
            "name" : "MARKETING AND COMMUNICATION",
            "examples" : [
                "BLOGGER",
                "BUSINESS DEVELOPER MANAGER",
                "COMMUNICATION",
                "COMMUNICATIONS",
                "COMMUNITY",
                "COMMUNITY EXPERT",
                "CONTENT WRITER",
                "COPYRIGHTER",
                "CUSTOMER SERVICE",
                "EDITOR",
                "HEAD OF MARKETING",
                "INFLUENCER",
                "MANAGING DIRECTOR",
                "MARKETING",
                "MARKETING ADVISOR",
                "MARKETING DIRECTOR",
                "MARKETING MANAGER",
                "MEDIA",
                "NEWS",
                "NEWS PUBLISHER",
                "PR",
                "PR MANAGER",
                "PROJECT MANAGER",
                "PUBLIC RELATIONS",
                "PUBLIC RELATIONS OFFICER",
                "PUBLISHER",
                "SPEAKER",
                "SALES",
                "STRATEGIST",
                "1WORLD WEST COAST",
                "AMBASSADOR",
                "BLOCKCHAIN AMBASSADOR",
                "BLOCKCHAIN EVANGELIST",
                "BRAND AMBASSADOR",
                "BRANDING",
                "BRANDING EXPERT",
                "CLIENT RELATIONS",
                "CRYPTO EVANGELIST",
                "CUSTOMER RELATIONS",
                "CUSTOMER SUCCESS",
                "CUSTOMER SUPPORT",
                "CUSTOMER SUPPORT SPECIALIST",
                "CUSTOMER SUPPORT TECHNICIAN",
                "DIGITAL MARKETER",
                "EVANGELIST",
                "GLOBAL AMBASSADOR",
                "GROWTH HACKER",
                "ICOBENCH EXPERT",
                "INTERNATIONAL RELATIONS",
                "MARKETER",
                "PARTNERSHIPS",
                "PIONEER",
                "SECRET CHALLENGE AMBASSADOR",
                "SOCIAL",
                "VIDEOMAKER"
            ]
        },
        {
            "name" : "NOT PERTINENT",
            "examples" : [
                "AFRICA",
                "ASIA",
                "CENTRAL AMERICA",
                "CHINA",
                "EASTERN EUROPE",
                "ENTHUSIAST",
                "EUROPEAN UNION",
                "JAPAN",
                "LEADERSHIP",
                "MIDDLE EAST",
                "NORTH AMERICA",
                "OCEANIA",
                "SOUTH AMERICA",
                "THE CARIBBEAN",
                "ZUMBA INSTRUCTOR",
                "BELARUS",
                "CANADA",
                "CONSUL",
                "DERMATOLOGIST",
                "ENVIRONMENT",
                "FOOTBALL CLUB",
                "FRENCH",
                "MODEL",
                "OLYMPIC CHAMPION",
                "PSYCHOLOGIST",
                "RENEWABLE ENERGY GENERATION",
                "SLOVAKIA",
                "SPANISH",
                "STUDENT LIAISON",
                "THE GROUP",
                "WOMEN COMMISSION"
            ]
        },
        {
            "name" : "OPERATIONS, SECURITY AND SUPPORT",
            "examples" : [
                "BLOCKCHAIN SECURITY",
                "COO",
                "CHIEF OPERATING",
                "CHIEF OPERATING OFFICER",
                "CHIEF SECURITY",
                "CHIEF SECURITY OFFICER",
                "OPERATION",
                "TECHNICAL SUPPORT",
                "CUSTOMER SATISFACTION TEAM",
                "CUSTOMER SUPPORT",
                "CUSTOMER SUPPORT ADMINISTRATOR",
                "CUSTOMER SUPPORT DEPARTMENT",
                "CYBER SECURITY",
                "DEVOPS",
                "DEV OPS",
                "DEV-OPS",
                "DISTRIBUTED SYSTEMS EXPERT",
                "INFORMATION SECURITY",
                "INFORMATION SECURITY OFFICER",
                "INTEGRATION SPECIALIST",
                "SECURITY",
                "SECURITY ARCHITECTURE",
                "SECURITY EXPERT",
                "SECURITY SPECIALIST",
                "SUPPORT",
                "SUPPORT SPECIALIST",
                "SYSTEM ADMINISTRATOR",
                "TECHNICAL EXPERT",
                "TELEPHONE SUPPORT"
            ]
        },
        {
            "name" : "PM, ANALIST AND DESIGNER",
            "examples" : [
                "BLOCKCHAIN ARCHITECT",
                "DATA ARCHITECT",
                "BLOCKCHAIN ANALYST",
                "BUSINESS ANALIST",
                "CREATIVE DIRECTOR",
                "TEAM LEADER",
                "PROJECT",
                "SYSTEM ARCHITECT",
                "ANALYST",
                "ARCHITECT",
                "BLOCKCHAIN LEADER",
                "BLOCKCHAIN SOLUTION ARCHITECT",
                "CREATIVE HEAD",
                "CRYPTO ANALYST",
                "MOBILE ARCHITECT",
                "MODERATOR",
                "PLATFORM ARCHITECT",
                "PRODUCER",
                "PROTOCOL ARCHITECT",
                "SCIENCE EXPERT",
                "SCRUM MASTER",
                "SENIOR ARCHITECT",
                "SENIOR SOFTWARE ARCHITECT",
                "SOFTWARE ARCHITECT",
                "SOLUTION ANALYST",
                "SOLUTION ARCHITECT",
                "SOLUTIONS ARCHITECT",
                "SYSTEM ANALYST",
                "TECHNICAL ARCHITECT",
                "TECHNICAL LEADER"
            ]
        },
        {
            "name" : "UNKNOWN",
            "examples" : [
                "",
                " "
            ]
        }
    ]

TERMS_ROLES = {
    "ADVISER" : "ADVISOR",	
    "ADVISING" : "ADVISOR",	
    "ADVISOR" : "ADVISOR",	
    "ADVISORY" : "ADVISOR",	
    "ADVOCATE" : "ADVISOR",	
    "ATTORNEY" : "ADVISOR",	
    "CCO" : "ADVISOR",	
    "COMPLIANCE" : "ADVISOR",	
    "CONSULTANT" : "ADVISOR",	
    "CONSULTING" : "ADVISOR",	
    "ENDORSER" : "ADVISOR",	
    "LAW" : "ADVISOR",	
    "LAWYER" : "ADVISOR",	
    "LEGAL" : "ADVISOR",	
    "MENTOR" : "ADVISOR",	
    "MENTORS" : "ADVISOR",	
    "PROFESSOR" : "ADVISOR",	
    "REGULATION" : "ADVISOR",	
    "STRATEGIC" : "ADVISOR",	
    "STRATEGY" : "ADVISOR",	
    "2D" : "DEVELOPER",	
    "3D" : "DEVELOPER",	
    "AI" : "DEVELOPER",	
    "ANDROID" : "DEVELOPER",	
    "ART" : "DEVELOPER",	
    "ARTIST" : "DEVELOPER",	
    "AUDIO" : "DEVELOPER",	
    "BACK" : "DEVELOPER",	
    "BACKEND" : "DEVELOPER",	
    "BACKOFFICE" : "DEVELOPER",	
    "BC" : "DEVELOPER",	
    "BI" : "DEVELOPER",	
    "CLIENT" : "DEVELOPER",	
    "CODER" : "DEVELOPER",	
    "COMPUTER" : "DEVELOPER",	
    "CONTENT" : "DEVELOPER",	
    "COPYWRITER" : "DEVELOPER",	
    "CREATIVE" : "DEVELOPER",	
    "CREATOR" : "DEVELOPER",	
    "CRYPTOGRAPHER" : "DEVELOPER",	
    "CRYPTOGRAPHY" : "DEVELOPER",	
    "DATA" : "DEVELOPER",	
    "DATABASE" : "DEVELOPER",	
    "DEEP" : "DEVELOPER",	
    "DESIGNER" : "DEVELOPER",	
    "DEV" : "DEVELOPER",	
    "DEVELOPER" : "DEVELOPER",	
    "DEVELOPMENT" : "DEVELOPER",	
    "ENGINEER" : "DEVELOPER",	
    "ENGINEERING" : "DEVELOPER",	
    "ETHEREUM" : "DEVELOPER",	
    "FRONT" : "DEVELOPER",	
    "FRONTEND" : "DEVELOPER",	
    "GAME" : "DEVELOPER",	
    "GRAPHIC" : "DEVELOPER",	
    "GRAPHICS" : "DEVELOPER",	
    "ILLUSTRATOR" : "DEVELOPER",	
    "INTELLIGENCE" : "DEVELOPER",	
    "INTERFACE" : "DEVELOPER",	
    "INTERN" : "DEVELOPER",	
    "IT" : "DEVELOPER",	
    "JAVA" : "DEVELOPER",	
    "JS" : "DEVELOPER",	
    "MACHINE" : "DEVELOPER",	
    "MATHEMATICIAN" : "DEVELOPER",	
    "MEMBER" : "DEVELOPER",	
    "MOBILE" : "DEVELOPER",	
    "MULTIMEDIA" : "DEVELOPER",	
    "PRODUCER" : "DEVELOPER",	
    "PROGRAMMER" : "DEVELOPER",	
    "PROGRAMMING" : "DEVELOPER",	
    "QA" : "DEVELOPER",	
    "QUALITY" : "DEVELOPER",	
    "QUANTITATIVE" : "DEVELOPER",	
    "PYTHON" : "DEVELOPER",	
    "RESEARCH" : "DEVELOPER",	
    "RESEARCHER" : "DEVELOPER",	
    "SCIENTIST" : "DEVELOPER",	
    "SOFTWARE" : "DEVELOPER",	
    "SOLIDITY" : "DEVELOPER",	
    "SOLUTION" : "DEVELOPER",	
    "SOLUTIONS" : "DEVELOPER",	
    "SMART" : "DEVELOPER",	
    "STACK" : "DEVELOPER",	
    "STATISTICIAN" : "DEVELOPER",	
    "STATISTICS" : "DEVELOPER",	
    "STYLIST" : "DEVELOPER",	
    "TECH" : "DEVELOPER",	
    "TECHNICAL" : "DEVELOPER",	
    "TECHNICIAN" : "DEVELOPER",	
    "TECHNOLOGICAL" : "DEVELOPER",	
    "TECHNOLOGIES" : "DEVELOPER",	
    "TECHNOLOGIST" : "DEVELOPER",	
    "TECHNOLOGY" : "DEVELOPER",	
    "TESTER" : "DEVELOPER",	
    "TESTING" : "DEVELOPER",	
    "TRANSLATIONS" : "DEVELOPER",	
    "TRANSLATOR" : "DEVELOPER",	
    "UI" : "DEVELOPER",	
    "USER" : "DEVELOPER",	
    "UX" : "DEVELOPER",	
    "VIDEO" : "DEVELOPER",	
    "VISUAL" : "DEVELOPER",	
    "WEB" : "DEVELOPER",	
    "WRITER" : "DEVELOPER",	
    "ACCOUNT" : "FINANCE AND ADMINISTRATION",	
    "ACCOUNTS" : "FINANCE AND ADMINISTRATION",	
    "ACCOUNTING" : "FINANCE AND ADMINISTRATION",	
    "ACCOUNTINGS" : "FINANCE AND ADMINISTRATION",	
    "ACCOUNTANT" : "FINANCE AND ADMINISTRATION",	
    "ADMIN" : "FINANCE AND ADMINISTRATION",	
    "ADMINISTRATION" : "FINANCE AND ADMINISTRATION",	
    "ADMINISTRATIVE" : "FINANCE AND ADMINISTRATION",	
    "ANALYTICS" : "FINANCE AND ADMINISTRATION",	
    "ASSET" : "FINANCE AND ADMINISTRATION",	
    "ASSETS" : "FINANCE AND ADMINISTRATION",	
    "ASSISTANT" : "FINANCE AND ADMINISTRATION",	
    "BANK" : "FINANCE AND ADMINISTRATION",	
    "BANKER" : "FINANCE AND ADMINISTRATION",	
    "BANKING" : "FINANCE AND ADMINISTRATION",	
    "BUSINESS" : "FINANCE AND ADMINISTRATION",	
    "COMMERCIAL" : "FINANCE AND ADMINISTRATION",	
    "COMPANY" : "FINANCE AND ADMINISTRATION",	
    "CONTROLLER" : "FINANCE AND ADMINISTRATION",	
    "CORPORATE" : "FINANCE AND ADMINISTRATION",	
    "ECONOMIC" : "FINANCE AND ADMINISTRATION",	
    "ECONOMICS" : "FINANCE AND ADMINISTRATION",	
    "ECONOMIST" : "FINANCE AND ADMINISTRATION",	
    "ESCROW" : "FINANCE AND ADMINISTRATION",	
    "FINANCE" : "FINANCE AND ADMINISTRATION",	
    "FINANCES" : "FINANCE AND ADMINISTRATION",	
    "FINANCING" : "FINANCE AND ADMINISTRATION",	
    "FINANCIAL" : "FINANCE AND ADMINISTRATION",	
    "FINTECH" : "FINANCE AND ADMINISTRATION",	
    "HR" : "FINANCE AND ADMINISTRATION",	
    "HUMAN" : "FINANCE AND ADMINISTRATION",	
    "INSURANCE" : "FINANCE AND ADMINISTRATION",	
    "MANAGING" : "FINANCE AND ADMINISTRATION",	
    "OFFICE" : "FINANCE AND ADMINISTRATION",	
    "PAYMENT" : "FINANCE AND ADMINISTRATION",	
    "PAYMENTS" : "FINANCE AND ADMINISTRATION",	
    "SECRETARY" : "FINANCE AND ADMINISTRATION",	
    "SECURITIES" : "FINANCE AND ADMINISTRATION",	
    "TRADE" : "FINANCE AND ADMINISTRATION",	
    "TRADER" : "FINANCE AND ADMINISTRATION",	
    "TRADING" : "FINANCE AND ADMINISTRATION",	
    "ASSOCIATE" : "FOUNDER",	
    "COFOUNDER" : "FOUNDER",	
    "ENTREPRENEUR" : "FOUNDER",	
    "FOUNDER" : "FOUNDER",	
    "FOUNDING" : "FOUNDER",	
    "OWNER" : "FOUNDER",	
    "PARTNER" : "FOUNDER",	
    "PRESIDENT" : "FOUNDER",	
    "SHAREHOLDER" : "FOUNDER",	
    "BUSINESSANGEL" : "INVESTOR",	
    "FUNDER" : "INVESTOR",	
    "FUNDRAISER" : "INVESTOR",	
    "INVESTMENT" : "INVESTOR",	
    "INVESTOR" : "INVESTOR",	
    "VENTURE" : "INVESTOR",	
    "CBDO" : "MANAGER",	
    "CDO" : "MANAGER",	
    "CEO" : "MANAGER",	
    "CFO" : "MANAGER",	
    "CHAIRMAN" : "MANAGER",	
    "CHIEF" : "MANAGER",	
    "CIO" : "MANAGER",	
    "CMO" : "MANAGER",	
    "COO" : "MANAGER",	
    "COORDINATOR" : "MANAGER",	
    "CPO" : "MANAGER",	
    "CSO" : "MANAGER",	
    "CTO" : "MANAGER",	
    "DIRECTOR" : "MANAGER",	
    "DIRECTORS" : "MANAGER",	
    "EXECUTIVE" : "MANAGER",	
    "HEAD" : "MANAGER",	
    "HEADING" : "MANAGER",	
    "LEAD" : "MANAGER",	
    "MANAGEMENT" : "MANAGER",	
    "MANAGER" : "MANAGER",	
    "PRINCIPAL" : "MANAGER",	
    "SVP" : "MANAGER",	
    "VP" : "MANAGER",	
    "ADVERTISER" : "MARKETING AND COMMUNICATION",
    "ADVERTISING" : "MARKETING AND COMMUNICATION",
    "AGENT" : "MARKETING AND COMMUNICATION",
    "BD" : "MARKETING AND COMMUNICATION",
    "BDM" : "MARKETING AND COMMUNICATION",
    "BDO" : "MARKETING AND COMMUNICATION",
    "COMMUNITY" : "MARKETING AND COMMUNICATION",
    "AMBASSADOR" : "MARKETING AND COMMUNICATION",
    "BLOGGER" : "MARKETING AND COMMUNICATION",
    "BRAND" : "MARKETING AND COMMUNICATION",
    "BRANDING" : "MARKETING AND COMMUNICATION",
    "COMMERCE" : "MARKETING AND COMMUNICATION",
    "COMMERCIALIZATION" : "MARKETING AND COMMUNICATION",
    "COMMUNICATION" : "MARKETING AND COMMUNICATION",
    "COMMUNICATIONS" : "MARKETING AND COMMUNICATION",
    "COPYRIGHTER" : "MARKETING AND COMMUNICATION",
    "COPYRIGHTING" : "MARKETING AND COMMUNICATION",
    "COPYRIGHT" : "MARKETING AND COMMUNICATION",
    "COUNTRY" : "MARKETING AND COMMUNICATION",
    "EDITOR" : "MARKETING AND COMMUNICATION",
    "EVANGELIST" : "MARKETING AND COMMUNICATION",
    "EXCHANGE" : "MARKETING AND COMMUNICATION",
    "GROWTH" : "MARKETING AND COMMUNICATION",
    "INFLUENCER" : "MARKETING AND COMMUNICATION",
    "MARKET" : "MARKETING AND COMMUNICATION",
    "MARKETEER" : "MARKETING AND COMMUNICATION",
    "MARKETER" : "MARKETING AND COMMUNICATION",
    "MARKETING" : "MARKETING AND COMMUNICATION",
    "MARKETPLACE" : "MARKETING AND COMMUNICATION",
    "MEDIA" : "MARKETING AND COMMUNICATION",
    "NEWS" : "MARKETING AND COMMUNICATION",
    "PARTNERSHIP" : "MARKETING AND COMMUNICATION",
    "PARTNERSHIPS" : "MARKETING AND COMMUNICATION",
    "PIONEER" : "MARKETING AND COMMUNICATION",
    "PR" : "MARKETING AND COMMUNICATION",
    "PRESS" : "MARKETING AND COMMUNICATION",
    "PROMOTION" : "MARKETING AND COMMUNICATION",
    "PUBLIC" : "MARKETING AND COMMUNICATION",
    "PUBLISHER" : "MARKETING AND COMMUNICATION",
    "REGION" : "MARKETING AND COMMUNICATION",
    "REGIONAL" : "MARKETING AND COMMUNICATION",
    "REPRESENTATIVE" : "MARKETING AND COMMUNICATION",
    "SALES" : "MARKETING AND COMMUNICATION",
    "SEO" : "MARKETING AND COMMUNICATION",
    "SMM" : "MARKETING AND COMMUNICATION",
    "SOCIAL" : "MARKETING AND COMMUNICATION",
    "SPEAKER" : "MARKETING AND COMMUNICATION",
    "STRATEGIST" : "MARKETING AND COMMUNICATION",
    "VIDEOMAKER" : "MARKETING AND COMMUNICATION",
    "CLOUD" : "OPERATIONS SECURITY AND SUPPORT",
    "CUSTOMER" : "OPERATIONS SECURITY AND SUPPORT",
    "CYBERSECURITY" : "OPERATIONS SECURITY AND SUPPORT",
    "DEVOPS" : "OPERATIONS SECURITY AND SUPPORT",
    "HARDWARE" : "OPERATIONS SECURITY AND SUPPORT",
    "INFRASTRUCTURE" : "OPERATIONS SECURITY AND SUPPORT",
    "INTEGRATION" : "OPERATIONS SECURITY AND SUPPORT",
    "NETWORK" : "OPERATIONS SECURITY AND SUPPORT",
    "NETWORKING" : "OPERATIONS SECURITY AND SUPPORT",
    "OPERATION" : "OPERATIONS SECURITY AND SUPPORT",
    "OPERATIONS" : "OPERATIONS SECURITY AND SUPPORT",
    "PLATFORM" : "OPERATIONS SECURITY AND SUPPORT",
    "SECURITY" : "OPERATIONS SECURITY AND SUPPORT",
    "SERVER" : "OPERATIONS SECURITY AND SUPPORT",
    "SUPPORT" : "OPERATIONS SECURITY AND SUPPORT",
    "SYSADMIN" : "OPERATIONS SECURITY AND SUPPORT",
    "SYSTEM" : "OPERATIONS SECURITY AND SUPPORT",
    "SYSTEMS" : "OPERATIONS SECURITY AND SUPPORT",
    "WEBMASTER" : "OPERATIONS SECURITY AND SUPPORT",
    "ANALYST" : "PM ANALIST AND DESIGNER",
    "ARCHITECT" : "PM ANALIST AND DESIGNER",
    "ARCHITECTURE" : "PM ANALIST AND DESIGNER",
    "LEADER" : "PM ANALIST AND DESIGNER",
    "MODERATOR" : "PM ANALIST AND DESIGNER",
    "PROJECT" : "PM ANALIST AND DESIGNER",
    "RISK" : "PM ANALIST AND DESIGNER",
    "TEAM" : "PM ANALIST AND DESIGNER"
}